FROM node:16-alpine as base

# Create app directory
WORKDIR /usr/app

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY package*.json ./

FROM base as test
# If you are building your code for production
# RUN npm ci --only=production
RUN npm ci --quiet
# Bundle app source
COPY . .
CMD ["npm", "test"]

FROM base as prod
RUN npm ci --only=production
COPY . .
CMD [ "node", "index.js" ]